### ISSUE TITLE
Caching for requests that doesn't have the last-modified header

### ISSUE THREAD

**Issue by morloderex** [jyggen/bnet#29]
@jyggen I have noticed that not every request on blizzards end currently returns a Last-Modified status like for instance the data endpoints for wow.

What would be your preferred way of handling this? 
Could it be as simple as caching the request for x number of days or hours at a time? 

What is your thoughts on this?

**Comment by jyggen** [comment]
I thought about this back when I implemented support for the `If-Modified-Since` and `Last-Modified` headers and the conclusion back then was to not cache requests without headers at all since I didn't really want the library to make assumptions/behave unexpectedly.

The data from the classes/races endpoints should preferably be stored in a database and only be updated once per expansion, but if people want to waste they rate limits on that data then I think we should let them. If Blizzard wanted us to cache these requests they would've added a `Last-Modified` header to the responses :)

**Comment by morloderex** [comment]
True, but neverless i think we should allow for setting a custom cache time just for the optionalism it creates.

**Comment by jyggen** [comment]
Closing this since it's now out-of-scope for this library.
